# app/config/security.yml 
security: 
    firewalls:
        extranet: 
            pattern: ^/extranet 
            provider: tiendas 
            anonymous: ~ 
            form_login: 
                login_path: /extranet/login 
                check_path: /extranet/login_check 
            logout: 
                path: extranet_logout
                 
        frontend: 
            pattern: ^/* 
            provider: usuarios 
            anonymous: ~ 
            form_login: 
                login_path: usuario_login 
                check_path: usuario_login_check 
                remember_me: true
                default_target_path: /usuario/compras
            logout: 
                path: usuario_logout
                target: /sitio/vuelve-pronto
            switch_user: true

    access_control: 
        - { path: ^/usuario/login, roles: IS_AUTHENTICATED_ANONYMOUSLY } 
        - { path: ^/usuario/registro, roles: IS_AUTHENTICATED_ANONYMOUSLY } 
        - { path: ^/usuario/*, roles: ROLE_USUARIO }
        - { path: ^/extranet/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/extranet/*, roles: ROLES_TIENDA }
    providers: 
        usuarios: 
            entity: { class: AppBundle\Entity\Usuario, property: email }
        tiendas:
            entity: { class: AppBundle\Entity\Tienda, property: login } 
    encoders: 
        AppBundle\Entity\Usuario: bcrypt
        AppBundle\Entity\Tienda: bcrypt

